### ISSUE TITLE
Length of error 

### ISSUE THREAD

**Issue by tonyrog** [victronenergy/dbus_modbustcp#1]
Hi
I think there is an error at
https://github.com/victronenergy/dbus_modbustcp/blob/master/adu.cpp:52  in function  QByteArray ADU::toQByteArray()
Error code length is set to 2, but unit_id, function_code and error_code has 3 bytes.

I can see that the Color Control GX send length 2 in this case. But I suspect that
this is wrong. Or is it?

**Comment by mpvader** [comment]
Hi Tony, we'll look into this and get back to you, thank you for the report

**Comment by mulderm** [comment]
Hi Tony,
Many thanks for pointing out this bug. It has been fixed.

Regards, Marcel
