### ISSUE TITLE
xls register File Missing Setting for ESS Battery Life.

### ISSUE THREAD

**Issue by optio50** [victronenergy/dbus_modbustcp#10]
CCGX-Modbus-TCP-register-list.xlsx

com.victronenergy.settings	ESS BatteryLife state	2900	uint16	1		/Settings/CGwacs/BatteryLife/State

Has 
0
1
2
3
4
5
6
7
missing #8
9
10
11

Missing number 8  "Optimized (With Battery Life)"

**Comment by izak** [comment]
Added to xlsx.
