### ISSUE TITLE
Regression: Missing register. solarcharger 777 PV Amps

### ISSUE THREAD

**Issue by optio50** [victronenergy/dbus_modbustcp#12]
Regression: Missing register. solarcharger 777 PV Amps

**Comment by mpvader** [comment]
Hi @optio50 , yes - we are working on that.
Thank you for the report. More details here:

https://community.victronenergy.com/questions/118710/venus-os-v280-breaks-modbus-tcp-register-777-pv-cu.html

i’ll close this issue - does not mean we are not working on this; we are, with urgency.

meanwhile, I recommend to rollback to v2.73
