### ISSUE TITLE
ModbusTCP mapping question

### ISSUE THREAD

**Issue by 3dGrabber** [victronenergy/dbus_modbustcp#3]
Do [attributes.csv](../blob/master/attributes.csv) and [unitid2di.csv](../blob/master/unitid2di.csv) correspond to the mapping in the Excel file found [here](https://www.victronenergy.com/panel-systems-remote-monitoring/color-control#whitepapers) ?

Regarding the Excel table:
How to determine the Unit ID for a given field in the first table?

I seem to be able to get the `com.victronenergy.vebus` fieds on ID 246, but not anything else...

**Comment by edevries-victron** [comment]
You're right: unit ID 246 relates to devices connected to the ve.bus port, which are represented as `com.victronenergy.vebus`.
The unit ID depends on how the device you want to read out is connected. Usually the ID depends on the communication port used to connect the device. The mapping is in unit2di.csv and the second tab of the excel file (both files are derived from the same source).
