### ISSUE TITLE
Incorrect unit of measurement for register 1052 in XLSX

### ISSUE THREAD

**Issue by sfstar** [victronenergy/dbus_modbustcp#30]
Hello and thank you for opening the code to the modbus server component of the victron ecosystem.
There seems to be a mismatch between the values documented and actually returned for the dbus path: /ErrorCode

The XLSX states:
<img width="1672" alt="image" src="https://github.com/victronenergy/dbus_modbustcp/assets/6717280/fac7c186-cbcb-440a-a331-67577650b1bb">

and attributes.csv contains:
'com.victronenergy.pvinverter,/Ac/Power,i,kW,1052,int32,1,W'

The value currently returned by 1052 is wattage based (as matches the attributes.csv file).
However, the XLSX states kW as the correct unit of measurement.
Is the XLSX incorrect or should the value returned be kW based but isn't encoded as such?

For reference the issue on my integrations issue tracker:
https://github.com/sfstar/hass-victron/issues/13

**Comment by sfstar** [comment]
@izak could you perhaps give me any insight as to how this discrepancy needs to be addressed/interpreted?

**Comment by izak** [comment]
This is already corrected in the xlsx. But thanks for reminding me that we need to update the one on the main website to match the 3.20 release.
