### ISSUE TITLE
Incorrect unit of measurement for register 2808

### ISSUE THREAD

**Issue by sfstar** [victronenergy/dbus_modbustcp#31]
Hello and thank you for opening the code to the modbus server component of the victron ecosystem.
There seems to be a mismatch between the values documented and actually returned for the dbus path: /Altitude

The XLSX states:
<img width="1543" alt="image" src="https://github.com/victronenergy/dbus_modbustcp/assets/6717280/bce234f2-b41b-45a4-a80e-f8d7c7109f79">

and attributes.csv contains:
'com.victronenergy.gps,/Altitude,d,m,2808,int32,10,R'

The value currently returned by 1052 should be in meters.
However, the XLSX states m/s as the correct unit of measurement.
I believe the XLSX should be updated to reflect the altitude as meters but I don't want to diverge from the XLSX without confirming it is wrong.

For reference the issue on my integrations issue tracker:
https://github.com/sfstar/hass-victron/issues/28

**Comment by askpatrickw** [comment]
It would be great if someone from the core team could confirm register 1052's units are defined incorrectly as meters per second and should be meters. 🙏

**Comment by izak** [comment]
Well clearly the unit is wrong, we need a unit of length, not one of speed! It's corrected in development and will reflect in the official document when we release the next version of Venus. Thank you for reporting this.
