### ISSUE TITLE
Address 3902 dupe?

### ISSUE THREAD

**Issue by petajoulecorp** [victronenergy/dbus_modbustcp#33]
In the current version of the .xlsx file, under com.victronenergy.acload, there seem to be two entries under the same address 3902

```
com.victronenergy.acload,L3 Power,3902,uint16,1,0 to 65535,/Ac/L3/Power,no,W,
com.victronenergy.acload,Serial number,3902,string[7],,,/Serial,no,,
```
making it impossible to determine whether "L3 Power" or "Serial number" is meant to be retrieved.

**Comment by izak** [comment]
Typo. It is correct in the attributes.csv file. It should be 3903.

Fixed in 007b7a.
