### ISSUE TITLE
Row 288: ESS Minimum SoC (unless grid fails) Scalefactor wrong?

### ISSUE THREAD

**Issue by warwickchapman** [victronenergy/dbus_modbustcp#7]
com.victronenergy.settings	ESS Minimum SoC (unless grid fails)

Scalefactor is 10 but on Venus you can adjust by 5.

Is 10 correct?

**Comment by izak** [comment]
10 is correct (not to be confused with 0.1). It allows you to set the minsoc in tenths of a percentage, which is even finer granularity than on the graphical interface.

**Comment by warwickchapman** [comment]
Got it ok.  Thanks.
